// <auto-generated/>
namespace PX.Generators.Tests.Examples
{
	partial class Example2
	{
		public new abstract class field1 : PX.Data.BQL.BqlString.Field<field1> { }
		public abstract class field6 : PX.Data.BQL.BqlString.Field<field6> { }
		public new abstract class field2 : PX.Data.BQL.BqlInt.Field<field2> { }
		public new abstract class field5 : PX.Data.BQL.BqlShort.Field<field5> { }
	}
}
