// <auto-generated/>
namespace PX.Generators.Tests.DacGeneratorsTests.Examples
{
    partial class NestingClass
    {
        partial class InnerNestingClass
        {
            partial class InnerNestedExample
            {
                public abstract class field1 : PX.Data.BQL.BqlString.Field<field1> { }
            }
        }
    }
}
