// <auto-generated/>
namespace PX.Generators.Tests.DacGeneratorsTests.Examples
{
    partial class NestedExample
    {
        partial class Inner
        {
            partial class InnerNested
            {
                public abstract class field1 : PX.Data.BQL.BqlString.Field<field1> { }
            }
        }
    }
}
